### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by fliptanedo** [NRDD-constraints/NRDD#1]
I am  unable to successfully import NRDD into a Jupyter notebook. I have downloaded the package as local files and run 
``` python
import NRDD_constraints as NR
```

As suggested in Appendix D of 1810.00607 and the README.md file. However, I end up with `UnicodeDecodeError`s and `UnicodeError`s. For example:
```
UnicodeDecodeError                        Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/numpy/lib/format.py in read_array(fp, allow_pickle, pickle_kwargs)
    692         try:
--> 693             array = pickle.load(fp, **pickle_kwargs)
    694         except UnicodeError as err:

UnicodeDecodeError: 'ascii' codec can't decode byte 0x9a in position 0: ordinal not in range(128)
```

See attached output.
[Direct Detection.pdf](https://github.com/NRDD-constraints/NRDD/files/3373969/Direct.Detection.pdf)

**Comment by fliptanedo** [comment]
As an update: importing in Python seems to work fine, but importing in a Jupyter notebook does not work. 

I am able 
![Screen Shot 2019-07-09 at 10 12 17 AM](https://user-images.githubusercontent.com/10454879/60909035-153e9c00-a232-11e9-9348-889073c3136a.png)
to make some progress in Jupyter by importing `unicode_literals`:
```python
from __future__ import unicode_literals
```

However, there is now some kind of pickle problem:
![Screen Shot 2019-07-09 at 10 12 17 AM](https://user-images.githubusercontent.com/10454879/60909046-1d96d700-a232-11e9-840e-c0b323de36ab.png)

**Comment by fliptanedo** [comment]
It looks like there are similar errors if I try to import using  Python 3, but in Python 2 it seems to work. Can you confirm that this is the intended system? (It would be helpful to note in the `README.md` file that the code is only for Python 2, if this is the case.

**Comment by NRDD-constraints** [comment]
The code was written in Python 2.7 and so was not compatible with Python 3. Also, the version of Scipy was playing a role. Now, the code is upgraded to Python 3 and relevant explanations about required libraries have been added to <code>README.md</code>. Thanks for pointing this out.
